import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/website/Header";
import Footer from "@/components/website/Footer";
import { Montserrat } from "next/font/google";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "iShop - Home",
  description: "Generated by create next app",
};
const montserrat = Montserrat({
  subsets: ["latin"], // Specify language subsets
  weight: ["400", "600"], // Specify font weights
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${montserrat.className} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
