import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "@/app/globals.css";
import SideBar from "@/components/admin/SideBar";
import Header from "@/components/admin/Header";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin Pannel",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"], // Specify language subsets
  weight: ["400", "600"], // Specify font weights
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${montserrat.className} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <div className="grid grid-cols-5">
          <div className="col-span-1">
            <SideBar />
          </div>
          <div className="col-span-4">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
